turtlebot3_waffle_sim:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  
  # Position Controllers ---------------------------------------
  left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_left_joint
    pid: {p: 1.0, i: 0.001, d: 0.01}
  right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_right_joint
    pid: {p: 1.0, i: 0.001, d: 0.01}

